class MaxAttemptsExceededError(Exception):
    """Исключение, возникающее при превышении максимального числа попыток выполнения операции."""
    pass
